INSERT INTO public.questions (
    chapter_number,
    description,
    explanation,
    choice_1,
    choice_2,
    choice_3,
    choice_4,
    correct_answer,
    question_number
) VALUES
(5, 'java.io.Fileクラスに関する説明として、正しいものを選びなさい。（１つ選択）',
 '未定',
 'パスを扱っているだけであって、ファイルやディレクトリそのものを表すわけではない',
 'ファイルは扱えるが、ディレクトリは扱えない',
 'ファイルやディレクトリそのものを扱うクラスである',
 'ファイルを扱うインスタンスを作ると、ディスク上にファイルが生成される',
 'A', 1),

(5, 'java.io.Fileクラスのメソッドで、ディレクトリ内の一覧をFileとして取得するためのものを選びなさい。（１つ選択）',
 '未定',
 'listメソッド',
 'filesメソッド',
 'listFilesメソッド',
 'getAllメソッド',
 'C', 2),

(5, 'テキストデータを読み込むためのクラスとして、正しいものを選びなさい。（１つ選択）',
 '未定',
 'java.io.InputStream',
 'java.io.Reader',
 'java.io.InputReader',
 'java.io.StreamReader',
 'B', 3),

(5, '写真データを扱うプログラムを開発している。より効率よく写真データを読み込むために使用するクラスとして正しいものを選びなさい。（１つ選択）',
 '未定',
 'java.io.FileReader',
 'java.io.InputStream',
 'java.io.BufferedReader',
 'java.io.BufferedInputStream',
 'D', 4),

(5, '次のコードの説明として、正しいものを選びなさい。（１つ選択）\n\nFileWriter out = new FileWriter("output.txt", false);',
 '未定',
 '常に新しいファイルを生成する',
 '対象のファイルが存在しなければ書き込まない',
 '追記モードで書き込む',
 '上書きモードで書き込む',
 'D', 5),

(5, 'java.io.BufferedWriterクラスに関する説明として、正しいものを選びなさい。（１つ選択）',
 '未定',
 'newLineメソッドは、改行コードとしてのキャリッジリターンのみを出力する',
 'writeメソッドを実行すると、ファイルの文字列が出力される',
 'flushメソッドはバッファとファイルを同期させる',
 'BufferedWriterクラスは、効率化のために直接ファイルに出力する',
 'C', 6),

(5, 'java.io.BufferedInputStreamクラスに関する説明として、正しいものを選びなさい。（１つ選択）',
 '未定',
 'readByteメソッドは、１バイトずつ読み込む',
 'readNBytesメソッドは、1024バイトずつ読み込む',
 'readKBytesメソッドは、1Kバイトずつ読み込む',
 'readAllBytesメソッドは、すべてのバイトを一度に読み込む',
 'D', 7),

(5, 'java.io.ConsoleクラスのreadPasswordメソッドの戻り値として、正しいものを選びなさい。（１つ選択）',
 '未定',
 'char[]',
 'String',
 'CharSequence',
 'InputStream',
 'A', 8),

(5, '次のプログラムをコンパイル、実行した時の結果として、正しいものを選びなさい。（１つ選択）\n\nimport java.util.Scanner;\n\npublic class Exe {\n    public static void main(String[] args) {\n        Scanner scan = new Scanner("A,B,C,D,E");\n        scan.useDelimiter(",");\n        try(scan) {\n            scan.next();\n            scan.next();\n            scan.next();\n            scan.next();\n            System.out.println(scan.next());\n        }\n    }\n}',
 '未定',
 '「E」と表示される',
 '「null」と表示される',
 'コンパイルエラーが発生する',
 '実行時に例外がスローされる',
 'A', 9),

(5, 'java.io.Serializableインタフェースに関する説明として、正しいものを選びなさい。（１つ選択）',
 '未定',
 'オブジェクトをシリアライズしたいクラスが実装するインタフェースである',
 'シリアライズ対象のクラスは、このインタフェースに定義されているserializeメソッドでシリアライズ処理の内容を実装しなければならない',
 'このインタフェースには、何もメソッドが定義されていない',
 'このインタフェースを実装しなくても、シリアライズは可能である',
 'C', 10),

(5, 'カスタム・シリアライズを行うときに、シリアライズ時に呼び出されるメソッドとして、正しいものを選びなさい。（１つ選択）',
 '未定',
 'readStreamメソッド',
 'readObjectメソッド',
 'writeStreamメソッド',
 'writeObjectメソッド',
 'D', 11),

(5, 'java.nio.file.Pathを使ったコードとして、コンパイルエラーになるものを選びなさい。（１つ選択）',
 '未定',
 'Path path = Paths.get("dir/sample.txt");',
 'Path path = Paths.get("dir", "sample.txt");',
 'Path path = new File("sample.txt").toPath();',
 'Path path = Files.get("sample.txt");',
 'D', 12),

(5, 'java.nio.file.Filesクラスを使ってファイルを作成するとき、誤って既存のファイルと同じパスを指定してしまった。結果として正しいものを選びなさい（１つ選択）',
 '未定',
 'プログラムは正しく終了し、既存のファイルは空のファイルで上書きされる',
 'プログラムは正しく終了し、既存のファイルはそのまま何も起こらない',
 '実行時に例外がスローされる',
 '結果を表すOptionalクラスが戻される',
 'C', 13),

(5, 'java.nio.file.Filesクラスを使って、新しいファイルを作成しようとしている。次のコードの説明として、正しいものを選びなさい（１つ選択）\n\nPath dir = Paths.get("a", "b");\nPath file = dir.resolve(Paths.get("data.txt"));\n\nFiles.createFile(file);',
 '未定',
 'b/aディレクトリ内にdata.txtができる',
 'a/bディレクトリ内にdata.txtができる',
 'aディレクトリ内にdata.txtができる',
 'bディレクトリ内にdata.txtができる',
 'B', 14),

(5, 'java.nio.file.Filesクラスの説明として、正しいものを選びなさい。（2つ選択）',
 '未定',
 'ファイルのコピーを行うには、copyメソッドを使う',
 'ファイルのコピーを行うには、copyメソッドを使う',
 'ファイルの移動を行うには、copyメソッドに移動オプションを指定する',
 'ファイルの移動を行うには、moveメソッドを使う',
 'AD', 15),

(5, 'java.nio.file.Filesクラスを使い、java.io.BufferedWriterを追記モードで取得したい。正しいものを選びなさい。（１つ選択）',
 '未定',
 'Path sample = Paths.get("sample.txt");\nBufferedWriter out = Files.newBufferedWriter(sample);',
 'Path sample = Paths.get("sample.txt");\nBufferedWriter out = \n    Files.newBufferedWriter(\n        sample,\n        StandardOpenOption.APPEND);',
 'Path sample = Paths.get("sample.txt");\nBufferedWriter out = Files.newBufferedWriter(sample, true);',
 'Path sample = Paths.get("sample.txt");\nBufferedWriter out = Files.newBufferedWriter(sample, false);',
 'B', 16),

(5, 'java.nio.file.Filesクラスのメソッドで、引数で渡したディレクトリの中にさらにサブディレクトリがあったとき、その中まで全て再帰的に探索するメソッドとして、正しいものを選びなさい。（１つ選択）',
 '未定',
 'listメソッド',
 'walkメソッド',
 'findメソッド',
 'listFilesメソッド',
 'B', 17),

(5, 'java.nio.file.FilesクラスのwalkFileTreeメソッドで利用するjava.nio.file.FileVisitorインタフェースがサポートするイベントとして、誤っているものを選びなさい。（１つ選択）',
 '未定',
 'ディレクトリに入る時',
 'ディレクトリを出る時',
 'ファイルの処理に失敗した時',
 'ファイルの処理が終了したとき',
 'D', 18);
